# Generated by Django 5.1.4 on 2025-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_cart_unique_together_cart_cart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_page_product',
            name='is_burmese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sell_page_product',
            name='စျေး',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell_page_product',
            name='ဒုတိယပုံ',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='sell_page_product',
            name='ဖော်ပြချက်',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sell_page_product',
            name='လျှော့စျေး',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sell_page_product',
            name='အဓိကပုံ',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='sell_page_product',
            name='အမည်',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
    ]
