# Generated by Django 5.0.6 on 2025-02-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_sell_page_product_is_burmese_sell_page_product_စ__and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.sell_page_product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.buy_page_product'),
        ),
    ]
