# Generated by Django 5.0.6 on 2025-02-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_wishlist_product_sell_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.sell_page_product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.buy_page_product'),
        ),
    ]
