# Generated by Django 5.0.6 on 2025-02-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_orderitem_product_sell_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('b_buyview', 'Buy'), ('bsell_view', 'Sell')], default='buy', max_length=10),
        ),
    ]
