# Generated by Django 5.0.6 on 2025-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_alter_cart_cart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('b_buyview', 'b_buyview'), ('bsell_view', 'bsell_view')], default='buy', max_length=10),
        ),
    ]
