# Generated by Django 5.0.6 on 2025-02-27 07:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_page_product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='sell_page_product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='sell_page_product',
            name='ဖော်ပြချက်',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
