# Generated by Django 5.0.6 on 2025-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_alter_buy_page_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_page_product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
